[formatting]
align_entries = false
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = false
compact_arrays = false
compact_inline_tables = false
column_width = 100
indent_tables = false
indent_entries = false
reorder_keys = false
allowed_blank_lines = 1
trailing_newline = true
